import { createRemoteRegistration } from './remoteRegistration'

export const federatedRemotes = [
  createRemoteRegistration({
    runtimeName: 'quizzes_courses',
    alias: 'quizzesCourses',
    entryPath: '/remotes/quizzes-courses/remoteEntry.js',
    moduleId: 'quizzesCourses/feature',
    componentExport: 'QuizzesCoursesComponent',
    basePath: '/quizzes-and-courses',
    routeName: 'quizzes-courses',
    featureName: 'Quizzes & Courses',
  }),
  createRemoteRegistration({
    runtimeName: 'mini_games',
    alias: 'miniGames',
    entryPath: '/remotes/mini-games/remoteEntry.js',
    moduleId: 'miniGames/feature',
    componentExport: 'MiniGamesComponent',
    basePath: '/mini-games',
    routeName: 'mini-games',
    featureName: 'Mini Games',
  }),
  createRemoteRegistration({
    runtimeName: 'chat_discussion',
    alias: 'chatDiscussion',
    entryPath: '/remotes/chat-discussion/remoteEntry.js',
    moduleId: 'chatDiscussion/feature',
    componentExport: 'ChatDiscussionComponent',
    basePath: '/chat-discussion',
    routeName: 'chat-discussion',
    featureName: 'Discussion Forum',
  }),
  createRemoteRegistration({
    runtimeName: 'quests_achievements',
    alias: 'questsAchievements',
    entryPath: '/remotes/quests-achievements/remoteEntry.js',
    moduleId: 'questsAchievements/feature',
    componentExport: 'QuestsAchievementsNotificationsComponent',
    basePath: '/quests-and-achievements',
    routeName: 'quests-achievements',
    featureName: 'Achievements & Notifications',
  }),
  createRemoteRegistration({
    runtimeName: 'leaderboard_analytics',
    alias: 'leaderboardAnalytics',
    entryPath: '/remotes/leaderboard-analytics/remoteEntry.js',
    moduleId: 'leaderboardAnalytics/feature',
    componentExport: 'LeaderboardAnalyticsComponent',
    basePath: '/analytics',
    routeName: 'leaderboard-analytics',
    featureName: 'Leaderboard & Analytics',
  }),
] as const