<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LanguageWise.Shared.Api.Tests</RootNamespace>
    <AssemblyName>LanguageWise.Shared.Api.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../backend/LanguageWise.Shared.Api/LanguageWise.Shared.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
