<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>LanguageWise.Student4.Db</RootNamespace>
    <AssemblyName>LanguageWise.Student4.Db</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sql/**/*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
