using System.Text.Json;
using LanguageWise.MiniGamesService.Api.Models;

namespace LanguageWise.MiniGamesService.Api.Services;

public interface IAssistantContextService
{
    AssistantContextResult GetContext(AssistantRouteContext routeContext);
}

/// <summary>
/// Builds the canonical context for the assistant. The mini games rules are static, so the
/// context is assembled locally from the same how-to-play steps the game pages show.
/// </summary>
public sealed class AssistantContextService : IAssistantContextService
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private static readonly object[] Games =
    [
        new
        {
            key = "guess-the-word",
            title = "Guess the Word",
            tagline = "Daily vocabulary challenge",
            howToPlay = new[]
            {
                "Find the hidden five-letter word within six guesses.",
                "Type a guess and press Guess — every letter is checked against the answer.",
                "A tile shows when a letter is in the right spot, in the word but in the wrong spot, or not in the word at all.",
                "Use the alphabet row below the board to keep track of the letters you have already tried."
            }
        },
        new
        {
            key = "word-search",
            title = "Word Search",
            tagline = "Find the connection",
            howToPlay = new[]
            {
                "Words from your course vocabulary are hidden as a chain of connected letters in the grid.",
                "Press and drag from letter to letter to trace a word, then release to submit it.",
                "Found words stay highlighted on the board and are ticked off in the list.",
                "Stuck? Spend a hint to reveal the start of a word — you only get a few."
            }
        },
        new
        {
            key = "associations",
            title = "Associations",
            tagline = "Make the associations",
            howToPlay = new[]
            {
                "All sixteen words secretly belong to four groups of four.",
                "Tap four words you think belong together, then press Submit group.",
                "A wrong group costs one mistake — the dots above the board show how many you have left.",
                "Find all four groups before running out of mistakes to win."
            }
        }
    ];

    private static readonly object[] VocabularyModes =
    [
        new
        {
            key = "content",
            title = "Content Focus",
            description = "Words come from the lessons the player has completed in their courses, so the games reinforce what they have already studied."
        },
        new
        {
            key = "ai",
            title = "AI Generation",
            description = "Words are generated by AI for the selected language. Used when no course vocabulary is unlocked yet or when the player wants extra variety."
        }
    ];

    public AssistantContextResult GetContext(AssistantRouteContext routeContext)
    {
        var currentGame = routeContext.RouteName is "guess-the-word" or "word-search" or "associations"
            ? routeContext.RouteName
            : null;

        return AssistantContextResult.Success(JsonSerializer.Serialize(new
        {
            page = routeContext.RouteName,
            platform = "LanguageWise",
            feature = "Mini Games",
            currentGame,
            selectedCourseCode = routeContext.CourseCode,
            selectedVocabularyMode = routeContext.Mode,
            vocabularyModes = VocabularyModes,
            games = Games
        }, JsonOptions));
    }
}

public sealed record AssistantContextResult(string? CanonicalContext, string? NotFoundMessage)
{
    public bool IsFound => CanonicalContext is not null;

    public static AssistantContextResult Success(string canonicalContext) =>
        new(canonicalContext, null);

    public static AssistantContextResult NotFound(string message) =>
        new(null, message);
}
