"""Writes `Plans/AgenticLoopPlan{GUID}.md` for the findings the human accepted."""

from __future__ import annotations

from pathlib import Path

from core.models import Finding, ImplementationPlan
from core.redaction import scrub
from core.session import format_timestamp, new_guid


def _bullets(items: list[str], empty: str = "_None recorded._") -> str:
    if not items:
        return empty
    return "\n".join(f"- {item}" for item in items)


def _code_list(items: list[str], empty: str = "_None recorded._") -> str:
    if not items:
        return empty
    return "\n".join(f"- `{item}`" for item in items)


def _blockquote(text: str, empty: str = "(no prompt recorded)") -> str:
    """Quote every line; a multi-line prompt must not escape the blockquote."""
    body = text.strip() or empty
    return "\n".join(f"> {line}" if line.strip() else ">" for line in body.splitlines())


def write_plan(
    *,
    plans_dir: Path,
    plan: ImplementationPlan,
    accepted: list[Finding],
    user_prompt: str,
    scope: Path,
    session_guid: str,
    round_number: int,
    model: str,
    plan_guid: str | None = None,
) -> Path:
    """Render the plan to markdown and return the absolute path it was written to."""
    directory = Path(plans_dir)
    directory.mkdir(parents=True, exist_ok=True)
    guid = plan_guid or new_guid()
    path = directory / f"AgenticLoopPlan{guid}.md"

    lines: list[str] = [
        f"# {plan.title or 'Implementation Plan'}",
        "",
        f"- **Plan ID:** {guid}",
        f"- **Session:** {session_guid} (round {round_number})",
        f"- **Created:** {format_timestamp()}",
        f"- **Model:** {model}",
        f"- **Review scope:** `{scope}`",
        "",
        "## Original Request",
        "",
        f"{_blockquote(user_prompt)}",
        "",
        "## Summary",
        "",
        plan.summary.strip() or "_No summary provided._",
        "",
        "## Accepted Findings",
        "",
    ]

    for index, finding in enumerate(accepted, start=1):
        lines.append(
            f"{index}. **{finding.title}** ({finding.severity.value}) — {finding.problem.strip()}"
        )
    lines.append("")

    if plan.suggested_order:
        lines.extend(["## Suggested Order of Work", ""])
        lines.extend(
            f"{index}. {title}" for index, title in enumerate(plan.suggested_order, start=1)
        )
        lines.append("")

    lines.extend(["## Implementation Items", ""])
    if not plan.items:
        lines.extend(["_The planning agent returned no items._", ""])

    for index, item in enumerate(plan.items, start=1):
        lines.extend(
            [
                f"### {index}. {item.finding_title}",
                "",
                f"**Problem:** {item.problem.strip() or '_Not restated._'}",
                "",
                f"**Goal:** {item.goal.strip() or '_Not stated._'}",
                "",
                "**Steps**",
                "",
            ]
        )
        if item.steps:
            for step in sorted(item.steps, key=lambda s: s.order):
                detail = f" — {step.details.strip()}" if step.details.strip() else ""
                files = (
                    f" (files: {', '.join(f'`{f}`' for f in step.files)})" if step.files else ""
                )
                lines.append(f"{step.order}. {step.action.strip()}{detail}{files}")
        else:
            lines.append("_No steps provided._")

        lines.extend(
            [
                "",
                "**Files to change**",
                "",
                _code_list(item.files_to_change),
                "",
                "**Tests to add or update**",
                "",
                _bullets(item.tests),
                "",
                "**Risks and trade-offs**",
                "",
                _bullets(item.risks),
                "",
                "**Acceptance criteria**",
                "",
                _bullets(item.acceptance_criteria),
                "",
            ]
        )

    if plan.open_questions:
        lines.extend(["## Open Questions", "", _bullets(plan.open_questions), ""])

    lines.extend(
        [
            "---",
            "",
            "_Generated by the Agentic Loop rubber duck. This tool is read-only: "
            "no source file was modified. Implement the steps above yourself, or hand "
            "this plan to a coding agent._",
            "",
        ]
    )

    path.write_text(scrub("\n".join(lines)), encoding="utf-8")
    return path
