<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>LanguageWise.QuestsAchievementsNotificationsService.Api</RootNamespace>
    <AssemblyName>LanguageWise.QuestsAchievementsNotificationsService.Api</AssemblyName>
  </PropertyGroup>

</Project>
