CREATE SCHEMA IF NOT EXISTS api;

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'web_anon') THEN
        CREATE ROLE web_anon NOLOGIN;
    END IF;
END
$$;

DROP TABLE IF EXISTS api.achievements CASCADE;
CREATE TABLE api.achievements (
    achievement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    image text NOT NULL,
    trigger text NOT NULL,
    progress_needed integer NOT NULL
);

DROP TABLE IF EXISTS api.user_achievements;
CREATE TABLE api.user_achievements (
    user_id integer NOT NULL,
    achievement_id integer NOT NULL REFERENCES api.achievements(achievement_id) ON DELETE CASCADE,
    progress integer NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, achievement_id)
);

DROP TABLE IF EXISTS api.user_preferences;
CREATE TABLE api.user_preferences (
    user_id integer PRIMARY KEY,
    email text,
    notify_all boolean NOT NULL DEFAULT true,
    notify_post_engagement boolean NOT NULL DEFAULT true,
    notify_course_completion boolean NOT NULL DEFAULT true,
    notify_quiz_results boolean NOT NULL DEFAULT true,
    notify_streaks boolean NOT NULL DEFAULT true,
    notify_achievements boolean NOT NULL DEFAULT true
);

DROP TABLE IF EXISTS api.notifications;
CREATE TABLE api.notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id text NOT NULL UNIQUE,
    user_id integer NOT NULL,
    trigger text NOT NULL,
    time timestamp with time zone NOT NULL,
    email_subject text NOT NULL,
    email_body text NOT NULL
);

GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA api TO web_anon;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA api TO web_anon;
