server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location = /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"healthy","service":"leaderboard-analytics-service-frontend"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
