<template>
	<main class="games-home">
		<div class="games-home__container">
			<div class="games-hero">
				<span class="games-chip">Train a little every day</span>
				<h1>Pick a game.<br /><span>Make it stick.</span></h1>
				<p>Three quick vocabulary workouts built from the words you have already unlocked in your courses.</p>
			</div>

			<section class="mode-picker" aria-label="Vocabulary source">
				<span class="language-picker__label">Word source</span>
				<div class="language-picker__options" role="group">
					<button
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': mode === 'content' }"
						:disabled="!modes.contentAvailable"
						:aria-pressed="mode === 'content'"
						@click="selectMode('content')"
					>
						Content Focus
					</button>
					<button
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': mode === 'ai' }"
						:disabled="!modes.aiAvailable"
						:aria-pressed="mode === 'ai'"
						@click="selectMode('ai')"
					>
						AI Generation
					</button>
				</div>
				<p v-if="!modes.contentAvailable" class="language-picker__hint">
					Course content is unavailable — playing with AI-generated words.
				</p>
				<p v-else-if="mode === 'ai'" class="language-picker__hint">
					Beginner words on fresh topics, generated by AI. Course progress is not used. Generation can take a few seconds when a game starts, please be patient.
				</p>
				<p v-else class="language-picker__hint">
					Words come from the lessons you have completed in your courses.
				</p>
			</section>

			<section v-if="modeLanguages.length > 0" class="language-picker" aria-label="Language your games use">
				<span class="language-picker__label">Practising</span>
				<div class="language-picker__options" role="group">
					<button
						v-for="language in modeLanguages"
						:key="language.code"
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': language.code === selectedLanguage }"
						:aria-pressed="language.code === selectedLanguage"
						@click="selectLanguage(language.code)"
					>
						{{ language.title }}
					</button>
				</div>
				<p v-if="mode === 'content'" class="language-picker__hint">Games only use words from the selected language. Complete lessons in other courses to unlock more.</p>
				<p v-else class="language-picker__hint">AI mode can generate words for any course language — pick whichever you want to practise.</p>
			</section>

			<section v-if="mode === 'content' && selectedLanguage" class="completion-tracker" aria-label="Your completed games in the selected language">
				<span class="completion-tracker__label">Completed in {{ selectedLanguageTitle }}</span>
				<ul class="completion-tracker__list">
					<li v-for="stat in completionStats" :key="stat.name" class="completion-tracker__item">
						<strong class="completion-tracker__count">{{ stat.count }}</strong>
						<span class="completion-tracker__name">{{ stat.name }}</span>
					</li>
				</ul>
			</section>

			<ul class="game-list">
				<li v-for="game in games" :key="game.name">
					<RouterLink class="game-card" :class="`game-card--${game.theme}`" :to="game.link">
						<div class="game-card__preview" :class="`game-card__preview--${game.theme}`" aria-hidden="true">
							<div v-if="game.theme === 'vocab'" class="vocab-preview">
								<span v-for="cell in 10" :key="cell" class="vocab-preview__cell" :class="{ 'is-filled': cell === 2 || cell === 7 }"></span>
							</div>
							<div v-else-if="game.theme === 'strings'" class="strings-preview">
								<span v-for="cell in 48" :key="cell" class="strings-preview__cell" :class="{ 'is-filled': cell === 5 || cell === 18 || cell === 31 || cell === 44 }"></span>
							</div>
							<div v-else class="associations-preview">
								<span v-for="cell in 16" :key="cell" class="associations-preview__cell" :class="{ 'is-filled': cell === 6 || cell === 11 }"></span>
							</div>
						</div>

						<div class="game-card__body">
							<span class="game-card__meta">Game {{ String(game.id).padStart(2, '0') }}</span>
							<h2>{{ game.name }}</h2>
							<p>{{ game.description }}</p>
							<span class="game-card__action">
								<span class="game-card__action-content">
									Play now <span aria-hidden="true">&#8594;</span>
								</span>
							</span>
						</div>
					</RouterLink>
				</li>
			</ul>
		</div>
	</main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import {
	ensureCourseCode,
	fetchCompletionStats,
	fetchGameModes,
	getAiLanguage,
	getCourseCode,
	getMode,
	setAiLanguage,
	setCourseCode,
	setMode
} from './api.js';

// Vocabulary modes available right now (content needs the courses service + unlocked words).
const modes = ref({ contentAvailable: true, aiAvailable: false, defaultMode: 'content', contentLanguages: [], aiLanguages: [] });
const mode = ref('content');

// Languages the current mode offers; the selected one scopes every game.
const selectedLanguage = ref(null);

// Successful completions per game type in the selected language, straight from the
// Games/GameAttempts tables via the stats endpoint.
const completions = ref(null);

const modeLanguages = computed(() => (mode.value === 'ai' ? modes.value.aiLanguages : modes.value.contentLanguages));

const selectedLanguageTitle = computed(
	() => modeLanguages.value.find((language) => language.code === selectedLanguage.value)?.title ?? selectedLanguage.value
);

const completionStats = computed(() => [
	{ name: 'Guess the word', count: completions.value?.guessTheWord ?? 0 },
	{ name: 'Word Search', count: completions.value?.wordSearch ?? 0 },
	{ name: 'Associations', count: completions.value?.associations ?? 0 }
]);

async function loadCompletions(courseCode) {
	if (!courseCode) {
		completions.value = null;
		return;
	}
	try {
		completions.value = await fetchCompletionStats(courseCode);
	} catch {
		completions.value = null;
	}
}

function selectLanguage(code) {
	selectedLanguage.value = code;
	if (mode.value === 'ai') {
		setAiLanguage(code);
	} else {
		setCourseCode(code);
		loadCompletions(code);
	}
}

function selectMode(next) {
	// Content focus can only be chosen while the courses service has vocabulary for the user.
	if (next === 'content' && !modes.value.contentAvailable) return;
	mode.value = next;
	setMode(next);
	// Re-select a valid language for the mode's list.
	const available = modeLanguages.value;
	const stored = next === 'ai' ? getAiLanguage() : getCourseCode();
	const stillValid = stored && available.some((language) => language.code === stored);
	const resolved = stillValid ? stored : available[0]?.code ?? null;
	selectedLanguage.value = resolved;
	if (next === 'ai') {
		if (resolved) setAiLanguage(resolved);
	} else if (resolved) {
		setCourseCode(resolved);
		loadCompletions(resolved);
	}
}

onMounted(async () => {
	try {
		modes.value = await fetchGameModes();
	} catch {
		// Without the modes endpoint we cannot know whether content is available; assume not,
		// so the UI degrades to AI generation (locked) which works standalone.
		modes.value = { contentAvailable: false, aiAvailable: true, defaultMode: 'ai', contentLanguages: [], aiLanguages: [] };
	}

	// Resolve the mode: stored choice when it is still usable, otherwise the backend default.
	const storedMode = getMode();
	const usable =
		(storedMode === 'content' && modes.value.contentAvailable) ||
		(storedMode === 'ai' && modes.value.aiAvailable);
	selectMode(usable ? storedMode : modes.value.defaultMode);
	loadCompletions(selectedLanguage.value);
});

// Relative links resolve correctly both under the gateway base (/mini-games/)
// and when served at the root in local dev.
const games = [
	{
		id: 1,
		name: 'Guess the word',
		link: { name: 'mini-games-guess-the-word' },
		theme: 'vocab',
		description: 'Guess the word, build your streak, and sharpen your language instincts.'
	},
	{
		id: 2,
		name: 'Word Search',
		link: { name: 'mini-games-word-search' },
		theme: 'strings',
		description: 'Follow the chain of letters and discover the words hiding in plain sight.'
	},
	{
		id: 3,
		name: 'Associations',
		link: { name: 'mini-games-associations' },
		theme: 'associations',
		description: 'Connect ideas, spot patterns, and make vocabulary stick together.'
	}
];
</script>
