<template>
	<main class="games-home">
		<div class="games-home__container">
			<div class="games-hero">
				<span class="games-chip">Train a little every day</span>
				<h1>Pick a game.<br /><span>Make it stick.</span></h1>
				<p>Three quick vocabulary workouts built from the words you have already unlocked in your courses.</p>
			</div>

			<section class="mode-picker" aria-label="Vocabulary source">
				<span class="language-picker__label">Word source</span>
				<div class="language-picker__options" role="group">
					<button
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': mode === 'content' }"
						:disabled="!modes.contentAvailable"
						:aria-pressed="mode === 'content'"
						@click="selectMode('content')"
					>
						Content Focus
					</button>
					<button
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': mode === 'ai' }"
						:disabled="!modes.aiAvailable"
						:aria-pressed="mode === 'ai'"
						@click="selectMode('ai')"
					>
						AI Generation
					</button>
				</div>
				<p v-if="!modes.contentAvailable" class="language-picker__hint">
					Course content is unavailable — playing with AI-generated words.
				</p>
				<p v-else-if="mode === 'ai'" class="language-picker__hint">
					Beginner words on fresh topics, generated by AI. Course progress is not used. Generation can take a few seconds when a game starts, please be patient.
				</p>
				<p v-else class="language-picker__hint">
					Words come from the lessons you have completed in your courses.
				</p>
			</section>

			<section v-if="modeLanguages.length > 0" class="language-picker" aria-label="Language your games use">
				<span class="language-picker__label">Practising</span>
				<div class="language-picker__options" role="group">
					<button
						v-for="language in modeLanguages"
						:key="language.code"
						type="button"
						class="language-picker__option"
						:class="{ 'is-active': language.code === selectedLanguage }"
						:aria-pressed="language.code === selectedLanguage"
						@click="selectLanguage(language.code)"
					>
						{{ language.title }}
					</button>
				</div>
				<p v-if="mode === 'content'" class="language-picker__hint">Games only use words from the selected language. Complete lessons in other courses to unlock more.</p>
				<p v-else class="language-picker__hint">AI mode can generate words for any course language — pick whichever you want to practise.</p>
			</section>

			<section v-if="mode === 'content' && selectedLanguage" class="completion-tracker" aria-label="Your completed games in the selected language">
				<span class="completion-tracker__label">Completed in {{ selectedLanguageTitle }}</span>
				<ul class="completion-tracker__list">
					<li v-for="stat in completionStats" :key="stat.name" class="completion-tracker__item">
						<strong class="completion-tracker__count">{{ stat.count }}</strong>
						<span class="completion-tracker__name">{{ stat.name }}</span>
					</li>
				</ul>
			</section>

			<ul class="game-list">
				<li v-for="game in games" :key="game.name">
					<a class="game-card" :class="`game-card--${game.theme}`" :href="game.link">
						<div class="game-card__preview" :class="`game-card__preview--${game.theme}`" aria-hidden="true">
							<div v-if="game.theme === 'vocab'" class="vocab-preview">
								<span v-for="cell in 10" :key="cell" class="vocab-preview__cell" :class="{ 'is-filled': cell === 2 || cell === 7 }"></span>
							</div>
							<div v-else-if="game.theme === 'strings'" class="strings-preview">
								<span v-for="cell in 48" :key="cell" class="strings-preview__cell" :class="{ 'is-filled': cell === 5 || cell === 18 || cell === 31 || cell === 44 }"></span>
							</div>
							<div v-else class="associations-preview">
								<span v-for="cell in 16" :key="cell" class="associations-preview__cell" :class="{ 'is-filled': cell === 6 || cell === 11 }"></span>
							</div>
						</div>

						<div class="game-card__body">
							<span class="game-card__meta">Game {{ String(game.id).padStart(2, '0') }}</span>
							<h2>{{ game.name }}</h2>
							<p>{{ game.description }}</p>
							<span class="game-card__action">
								<span class="game-card__action-content">
									Play now <span aria-hidden="true">&#8594;</span>
								</span>
							</span>
						</div>
					</a>
				</li>
			</ul>
		</div>
	</main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import {
	ensureCourseCode,
	fetchCompletionStats,
	fetchGameModes,
	getAiLanguage,
	getCourseCode,
	getMode,
	setAiLanguage,
	setCourseCode,
	setMode
} from './api.js';

// Vocabulary modes available right now (content needs the courses service + unlocked words).
const modes = ref({ contentAvailable: true, aiAvailable: false, defaultMode: 'content', contentLanguages: [], aiLanguages: [] });
const mode = ref('content');

// Languages the current mode offers; the selected one scopes every game.
const selectedLanguage = ref(null);

// Successful completions per game type in the selected language, straight from the
// Games/GameAttempts tables via the stats endpoint.
const completions = ref(null);

const modeLanguages = computed(() => (mode.value === 'ai' ? modes.value.aiLanguages : modes.value.contentLanguages));

const selectedLanguageTitle = computed(
	() => modeLanguages.value.find((language) => language.code === selectedLanguage.value)?.title ?? selectedLanguage.value
);

const completionStats = computed(() => [
	{ name: 'Guess the word', count: completions.value?.guessTheWord ?? 0 },
	{ name: 'Word Search', count: completions.value?.wordSearch ?? 0 },
	{ name: 'Associations', count: completions.value?.associations ?? 0 }
]);

async function loadCompletions(courseCode) {
	if (!courseCode) {
		completions.value = null;
		return;
	}
	try {
		completions.value = await fetchCompletionStats(courseCode);
	} catch {
		completions.value = null;
	}
}

function selectLanguage(code) {
	selectedLanguage.value = code;
	if (mode.value === 'ai') {
		setAiLanguage(code);
	} else {
		setCourseCode(code);
		loadCompletions(code);
	}
}

function selectMode(next) {
	// Content focus can only be chosen while the courses service has vocabulary for the user.
	if (next === 'content' && !modes.value.contentAvailable) return;
	mode.value = next;
	setMode(next);
	// Re-select a valid language for the mode's list.
	const available = modeLanguages.value;
	const stored = next === 'ai' ? getAiLanguage() : getCourseCode();
	const stillValid = stored && available.some((language) => language.code === stored);
	const resolved = stillValid ? stored : available[0]?.code ?? null;
	selectedLanguage.value = resolved;
	if (next === 'ai') {
		if (resolved) setAiLanguage(resolved);
	} else if (resolved) {
		setCourseCode(resolved);
		loadCompletions(resolved);
	}
}

onMounted(async () => {
	try {
		modes.value = await fetchGameModes();
	} catch {
		// Without the modes endpoint we cannot know whether content is available; assume not,
		// so the UI degrades to AI generation (locked) which works standalone.
		modes.value = { contentAvailable: false, aiAvailable: true, defaultMode: 'ai', contentLanguages: [], aiLanguages: [] };
	}

	// Resolve the mode: stored choice when it is still usable, otherwise the backend default.
	const storedMode = getMode();
	const usable =
		(storedMode === 'content' && modes.value.contentAvailable) ||
		(storedMode === 'ai' && modes.value.aiAvailable);
	selectMode(usable ? storedMode : modes.value.defaultMode);
	loadCompletions(selectedLanguage.value);
});

// Relative links resolve correctly both under the gateway base (/mini-games/)
// and when served at the root in local dev.
const games = [
	{
		id: 1,
		name: 'Guess the word',
		link: 'game/guess-the-word',
		theme: 'vocab',
		description: 'Guess the word, build your streak, and sharpen your language instincts.'
	},
	{
		id: 2,
		name: 'Word Search',
		link: 'game/word-search',
		theme: 'strings',
		description: 'Follow the chain of letters and discover the words hiding in plain sight.'
	},
	{
		id: 3,
		name: 'Associations',
		link: 'game/associations',
		theme: 'associations',
		description: 'Connect ideas, spot patterns, and make vocabulary stick together.'
	}
];
</script>

<style scoped>
.games-home {
	min-height: 100vh;
	background: radial-gradient(circle at 85% 8%, #e0e7ff 0, transparent 30%), #f6f7fb;
}

.games-home__container {
	padding: 38px clamp(24px, 3.5vw, 50px) 42px;
}

.games-hero {
	max-width: 780px;
}

.games-chip {
	display: inline-block;
	margin-bottom: 20px;
	padding: 6px 14px;
	border-radius: 999px;
	color: #4338ca;
	background: #eef2ff;
	font-size: 0.82rem;
	font-weight: 650;
}

.games-hero h1 {
	margin: 0;
	font-size: clamp(2.8rem, 6vw, 5rem);
	font-weight: 800;
	line-height: 1.03;
	letter-spacing: -0.055em;
}

.games-hero h1 span {
	color: #4f46e5;
}

.games-hero p {
	max-width: 630px;
	margin: 24px 0 0;
	color: #667085;
	font-size: 1.2rem;
	line-height: 1.7;
}

.language-picker,
.mode-picker {
	margin: 28px 0 0;
	padding: 16px 20px;
	border: 1px solid #e7e9f0;
	border-radius: 18px;
	background: white;
}

.mode-picker {
	margin-top: 20px;
}

.language-picker__option:disabled {
	opacity: 0.45;
	cursor: not-allowed;
}

.language-picker__label {
	display: block;
	margin-bottom: 10px;
	color: #4338ca;
	font-size: 0.78rem;
	font-weight: 700;
	letter-spacing: 0.08em;
	text-transform: uppercase;
}

.language-picker__options {
	display: flex;
	flex-wrap: wrap;
	gap: 8px;
}

.language-picker__option {
	padding: 8px 18px;
	border: 1.5px solid #d6dae6;
	border-radius: 999px;
	color: #475467;
	background: #f8f9fc;
	font-size: 0.95rem;
	font-weight: 600;
	cursor: pointer;
	transition: border-color 0.15s ease, background 0.15s ease, color 0.15s ease;
}

.language-picker__option:hover,
.language-picker__option:focus-visible {
	border-color: #4f46e5;
	color: #4338ca;
}

.language-picker__option:focus-visible {
	outline: 3px solid rgba(79, 70, 229, 0.28);
	outline-offset: 2px;
}

.language-picker__option.is-active {
	border-color: #4f46e5;
	color: white;
	background: #4f46e5;
}

.language-picker__hint {
	margin: 12px 0 0;
	color: #98a2b3;
	font-size: 0.85rem;
}

.completion-tracker {
	display: flex;
	align-items: center;
	flex-wrap: wrap;
	gap: 12px 24px;
	margin: 16px 0 0;
	padding: 14px 20px;
	border: 1px solid #e7e9f0;
	border-radius: 18px;
	background: white;
}

.completion-tracker__label {
	color: #4338ca;
	font-size: 0.78rem;
	font-weight: 700;
	letter-spacing: 0.08em;
	text-transform: uppercase;
}

.completion-tracker__list {
	display: flex;
	flex-wrap: wrap;
	gap: 10px;
	margin: 0;
	padding: 0;
	list-style: none;
}

.completion-tracker__item {
	display: inline-flex;
	align-items: baseline;
	gap: 6px;
	padding: 6px 14px;
	border-radius: 999px;
	background: #eef2ff;
}

.completion-tracker__count {
	color: #4f46e5;
	font-size: 1rem;
	font-weight: 800;
}

.completion-tracker__name {
	color: #475467;
	font-size: 0.85rem;
	font-weight: 600;
}

.game-list {
	display: grid;
	grid-template-columns: repeat(3, minmax(0, 1fr));
	gap: 20px;
	margin: 42px 0 0;
	padding: 0;
	list-style: none;
}

.game-list li {
	min-width: 0;
}

.game-card {
	position: relative;
	display: flex;
	height: 100%;
	flex-direction: column;
	overflow: hidden;
	border: 1px solid #e7e9f0;
	border-radius: 24px;
	color: inherit;
	background: white;
	text-decoration: none;
	transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.game-card:hover,
.game-card:focus-visible {
	box-shadow: 0 18px 40px rgba(31, 41, 55, 0.1);
	transform: translateY(-6px);
}

.game-card:focus-visible {
	outline: 3px solid rgba(79, 70, 229, 0.28);
	outline-offset: 3px;
}

.game-card__preview {
	display: grid;
	min-height: 13rem;
	padding: 1.5rem;
	place-items: center;
}

.game-card__preview--vocab {
	background: #e6f3f2;
}

.game-card__preview--strings {
	background: #fff1dc;
}

.game-card__preview--associations {
	background: #e9edff;
}

.vocab-preview {
	display: grid;
	grid-template-columns: repeat(5, 2.25rem);
	grid-template-rows: repeat(2, 2.25rem);
	gap: 0.4rem;
}

.vocab-preview__cell {
	border: 2px solid #1c2b45;
	background: rgba(255, 255, 255, 0.7);
}

.vocab-preview__cell.is-filled {
	border-color: #10897a;
	background: #10897a;
}

.strings-preview {
	display: grid;
	grid-template-columns: repeat(6, 1.55rem);
	grid-template-rows: repeat(8, 1.55rem);
	gap: 0.35rem;
	transform: rotate(-3deg);
}

.strings-preview__cell {
	border: 2px solid #9d6a28;
	background: rgba(255, 255, 255, 0.75);
}

.strings-preview__cell.is-filled {
	border-color: #d87832;
	background: #d87832;
}

.associations-preview {
	display: grid;
	grid-template-columns: repeat(4, 3.1rem);
	grid-template-rows: repeat(4, 3.1rem);
	gap: 0.45rem;
}

.associations-preview__cell {
	border: 2px solid #4254a4;
	border-radius: 0.7rem;
	background: rgba(255, 255, 255, 0.72);
}

.associations-preview__cell.is-filled {
	border-color: #4254a4;
	background: #4254a4;
}

.game-card__body {
	display: flex;
	flex: 1;
	flex-direction: column;
	padding: 24px;
}

.game-card__meta {
	color: #6366f1;
	font-size: 0.78rem;
	font-weight: 800;
	letter-spacing: 0.08em;
	text-transform: uppercase;
}

/* Each card picks up the accent colour of the game page it links to. */
.game-card--vocab .game-card__meta,
.game-card--vocab .game-card__action-content {
	color: #10897a;
}

.game-card--strings .game-card__meta,
.game-card--strings .game-card__action-content {
	color: #b45309;
}

.game-card--associations .game-card__meta,
.game-card--associations .game-card__action-content {
	color: #4254a4;
}

.game-card h2 {
	margin: 14px 0 8px;
	font-size: 1.5rem;
}

.game-card__body p {
	margin: 0;
	min-height: 48px;
	color: #667085;
	line-height: 1.5;
}

.game-card__action {
	display: flex;
	margin-top: 26px;
	align-items: center;
	justify-content: space-between;
	font-weight: 700;
}

.game-card__action-content {
	display: inline-flex;
	width: 100%;
	align-items: center;
	justify-content: space-between;
	gap: 12px;
}

.game-card__action-content span {
	display: inline-block;
	transition: transform 0.16s ease;
}

.game-card:hover .game-card__action-content span,
.game-card:focus-visible .game-card__action-content span {
	transform: translateX(0.25rem);
}

@media (max-width: 1100px) {
	.game-list {
		grid-template-columns: repeat(2, minmax(0, 1fr));
	}
}

@media (max-width: 600px) {
	.games-hero h1 {
		font-size: 2.7rem;
	}

	.game-list {
		grid-template-columns: minmax(0, 1fr);
	}

	.game-card__preview {
		min-height: 11rem;
	}
}
</style>